var keyboard = require('../');
var color = 200;
keyboard.color('left', color, color, color);
keyboard.color('middle', color, color, color);
keyboard.color('right', color, color, color);
keyboard.color('logo', color, color, color);
keyboard.color('frontLeft', color, color, color);
keyboard.color('frontRight', color, color, color);
keyboard.color('mouse', color, color, color);